// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package db

import (
	"context"
)

const getDraftByID = `-- name: GetDraftByID :one
SELECT id, post_id, final_text, user_id, created_at FROM drafts WHERE id = ?
`

func (q *Queries) GetDraftByID(ctx context.Context, id int64) (Draft, error) {
	row := q.db.QueryRowContext(ctx, getDraftByID, id)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.FinalText,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
