// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: draft_media.sql

package db

import (
	"context"
	"database/sql"
)

const countMediaKindsByDraft = `-- name: CountMediaKindsByDraft :many
SELECT kind, COUNT(*) AS cnt FROM draft_media WHERE draft_id = ? GROUP BY kind
`

type CountMediaKindsByDraftRow struct {
	Kind string `json:"kind"`
	Cnt  int64  `json:"cnt"`
}

func (q *Queries) CountMediaKindsByDraft(ctx context.Context, draftID int64) ([]CountMediaKindsByDraftRow, error) {
	rows, err := q.db.QueryContext(ctx, countMediaKindsByDraft, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMediaKindsByDraftRow
	for rows.Next() {
		var i CountMediaKindsByDraftRow
		if err := rows.Scan(&i.Kind, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDraftMedia = `-- name: CreateDraftMedia :exec
INSERT INTO draft_media (
  draft_id, kind, origin_media_id,
  file_id, url, position
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type CreateDraftMediaParams struct {
	DraftID       int64          `json:"draft_id"`
	Kind          string         `json:"kind"`
	OriginMediaID interface{}    `json:"origin_media_id"`
	FileID        sql.NullString `json:"file_id"`
	Url           sql.NullString `json:"url"`
	Position      int64          `json:"position"`
}

func (q *Queries) CreateDraftMedia(ctx context.Context, arg CreateDraftMediaParams) error {
	_, err := q.db.ExecContext(ctx, createDraftMedia,
		arg.DraftID,
		arg.Kind,
		arg.OriginMediaID,
		arg.FileID,
		arg.Url,
		arg.Position,
	)
	return err
}

const listDraftMedia = `-- name: ListDraftMedia :many
SELECT id, draft_id, kind, origin_media_id, file_id, url, position, created_at FROM draft_media WHERE draft_id = ?
`

func (q *Queries) ListDraftMedia(ctx context.Context, draftID int64) ([]DraftMedium, error) {
	rows, err := q.db.QueryContext(ctx, listDraftMedia, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftMedium
	for rows.Next() {
		var i DraftMedium
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.Kind,
			&i.OriginMediaID,
			&i.FileID,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
