// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: draft_media.sql

package db

import (
	"context"
)

const listDraftMedia = `-- name: ListDraftMedia :many
SELECT id, draft_id, kind, origin_media_id, file_id, url, position, created_at FROM draft_media WHERE draft_id = ?
`

func (q *Queries) ListDraftMedia(ctx context.Context, draftID int64) ([]DraftMedium, error) {
	rows, err := q.db.QueryContext(ctx, listDraftMedia, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftMedium
	for rows.Next() {
		var i DraftMedium
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.Kind,
			&i.OriginMediaID,
			&i.FileID,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
