// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AllowedUser struct {
	UserID   int64          `json:"user_id"`
	Username sql.NullString `json:"username"`
	AddedAt  time.Time      `json:"added_at"`
}

type Draft struct {
	ID        int64     `json:"id"`
	PostID    int64     `json:"post_id"`
	FinalText string    `json:"final_text"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type DraftMedium struct {
	ID            int64          `json:"id"`
	DraftID       int64          `json:"draft_id"`
	Kind          string         `json:"kind"`
	OriginMediaID interface{}    `json:"origin_media_id"`
	FileID        sql.NullString `json:"file_id"`
	Url           sql.NullString `json:"url"`
	Position      int64          `json:"position"`
	CreatedAt     time.Time      `json:"created_at"`
}

type PendingAction struct {
	ChatID    int64         `json:"chat_id"`
	Action    string        `json:"action"`
	PostID    sql.NullInt64 `json:"post_id"`
	DraftID   sql.NullInt64 `json:"draft_id"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type Post struct {
	ID          int64        `json:"id"`
	SourceID    int64        `json:"source_id"`
	ExternalID  string       `json:"external_id"`
	RawText     string       `json:"raw_text"`
	PublishedAt sql.NullTime `json:"published_at"`
	FetchedAt   time.Time    `json:"fetched_at"`
	Status      string       `json:"status"`
}

type PostMedium struct {
	ID       int64  `json:"id"`
	PostID   int64  `json:"post_id"`
	Kind     string `json:"kind"`
	Url      string `json:"url"`
	Position int64  `json:"position"`
}

type Schedule struct {
	ID           int64       `json:"id"`
	DraftID      int64       `json:"draft_id"`
	TargetChatID int64       `json:"target_chat_id"`
	ScheduledAt  time.Time   `json:"scheduled_at"`
	Status       string      `json:"status"`
	S            interface{} `json:"s"`
}

type Source struct {
	ID            int64  `json:"id"`
	ChannelHandle string `json:"channel_handle"`
	Active        int64  `json:"active"`
}
