// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_replies.sql

package db

import (
	"context"
)

const createPendingReply = `-- name: CreatePendingReply :exec
INSERT INTO pending_replies (chat_id, prompt_message_id, action, draft_id, origin)
VALUES (?, ?, ?, ?, ?)
`

type CreatePendingReplyParams struct {
	ChatID          int64  `json:"chat_id"`
	PromptMessageID int64  `json:"prompt_message_id"`
	Action          string `json:"action"`
	DraftID         int64  `json:"draft_id"`
	Origin          string `json:"origin"`
}

func (q *Queries) CreatePendingReply(ctx context.Context, arg CreatePendingReplyParams) error {
	_, err := q.db.ExecContext(ctx, createPendingReply,
		arg.ChatID,
		arg.PromptMessageID,
		arg.Action,
		arg.DraftID,
		arg.Origin,
	)
	return err
}

const deletePendingReply = `-- name: DeletePendingReply :exec
DELETE FROM pending_replies WHERE chat_id = ? AND prompt_message_id = ?
`

type DeletePendingReplyParams struct {
	ChatID          int64 `json:"chat_id"`
	PromptMessageID int64 `json:"prompt_message_id"`
}

func (q *Queries) DeletePendingReply(ctx context.Context, arg DeletePendingReplyParams) error {
	_, err := q.db.ExecContext(ctx, deletePendingReply, arg.ChatID, arg.PromptMessageID)
	return err
}

const getPendingReply = `-- name: GetPendingReply :one
SELECT chat_id, prompt_message_id, "action", draft_id, origin, created_at FROM pending_replies WHERE chat_id = ? AND prompt_message_id = ?
`

type GetPendingReplyParams struct {
	ChatID          int64 `json:"chat_id"`
	PromptMessageID int64 `json:"prompt_message_id"`
}

func (q *Queries) GetPendingReply(ctx context.Context, arg GetPendingReplyParams) (PendingReply, error) {
	row := q.db.QueryRowContext(ctx, getPendingReply, arg.ChatID, arg.PromptMessageID)
	var i PendingReply
	err := row.Scan(
		&i.ChatID,
		&i.PromptMessageID,
		&i.Action,
		&i.DraftID,
		&i.Origin,
		&i.CreatedAt,
	)
	return i, err
}
