// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_media.sql

package db

import (
	"context"
)

const addPostMedia = `-- name: AddPostMedia :one
INSERT INTO post_media (post_id, kind, url, position) VALUES (?, ?, ?, ?) RETURNING id, post_id, kind, url, position
`

type AddPostMediaParams struct {
	PostID   int64  `json:"post_id"`
	Kind     string `json:"kind"`
	Url      string `json:"url"`
	Position int64  `json:"position"`
}

func (q *Queries) AddPostMedia(ctx context.Context, arg AddPostMediaParams) (PostMedium, error) {
	row := q.db.QueryRowContext(ctx, addPostMedia,
		arg.PostID,
		arg.Kind,
		arg.Url,
		arg.Position,
	)
	var i PostMedium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Kind,
		&i.Url,
		&i.Position,
	)
	return i, err
}

const listPostMedia = `-- name: ListPostMedia :many
SELECT id, post_id, kind, url, position FROM post_media WHERE post_id = ? ORDER BY position ASC
`

func (q *Queries) ListPostMedia(ctx context.Context, postID int64) ([]PostMedium, error) {
	rows, err := q.db.QueryContext(ctx, listPostMedia, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostMedium
	for rows.Next() {
		var i PostMedium
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Kind,
			&i.Url,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
