// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_media.sql

package db

import (
	"context"
	"database/sql"
)

const addPostMedia = `-- name: AddPostMedia :one
INSERT INTO post_media (post_id, kind, url, position) VALUES (?, ?, ?, ?) RETURNING id, post_id, kind, url, file_id, position
`

type AddPostMediaParams struct {
	PostID   int64  `json:"post_id"`
	Kind     string `json:"kind"`
	Url      string `json:"url"`
	Position int64  `json:"position"`
}

func (q *Queries) AddPostMedia(ctx context.Context, arg AddPostMediaParams) (PostMedium, error) {
	row := q.db.QueryRowContext(ctx, addPostMedia,
		arg.PostID,
		arg.Kind,
		arg.Url,
		arg.Position,
	)
	var i PostMedium
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Kind,
		&i.Url,
		&i.FileID,
		&i.Position,
	)
	return i, err
}

const countMediaKindsByPost = `-- name: CountMediaKindsByPost :many
SELECT kind, COUNT(*) AS cnt FROM post_media WHERE post_id = ? GROUP BY kind
`

type CountMediaKindsByPostRow struct {
	Kind string `json:"kind"`
	Cnt  int64  `json:"cnt"`
}

func (q *Queries) CountMediaKindsByPost(ctx context.Context, postID int64) ([]CountMediaKindsByPostRow, error) {
	rows, err := q.db.QueryContext(ctx, countMediaKindsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMediaKindsByPostRow
	for rows.Next() {
		var i CountMediaKindsByPostRow
		if err := rows.Scan(&i.Kind, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostMedia = `-- name: ListPostMedia :many
SELECT id, post_id, kind, url, file_id, position FROM post_media WHERE post_id = ? ORDER BY position ASC
`

func (q *Queries) ListPostMedia(ctx context.Context, postID int64) ([]PostMedium, error) {
	rows, err := q.db.QueryContext(ctx, listPostMedia, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostMedium
	for rows.Next() {
		var i PostMedium
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Kind,
			&i.Url,
			&i.FileID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPostMediaFileID = `-- name: SetPostMediaFileID :exec
UPDATE post_media SET file_id = ? WHERE id = ?
`

type SetPostMediaFileIDParams struct {
	FileID sql.NullString `json:"file_id"`
	ID     int64          `json:"id"`
}

func (q *Queries) SetPostMediaFileID(ctx context.Context, arg SetPostMediaFileIDParams) error {
	_, err := q.db.ExecContext(ctx, setPostMediaFileID, arg.FileID, arg.ID)
	return err
}
