// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"database/sql"
)

const upsertPost = `-- name: UpsertPost :one
INSERT INTO posts (source_id, external_id, raw_text, published_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(source_id, external_id) DO NOTHING
RETURNING id, source_id, external_id, raw_text, published_at, fetched_at, status
`

type UpsertPostParams struct {
	SourceID    int64        `json:"source_id"`
	ExternalID  string       `json:"external_id"`
	RawText     string       `json:"raw_text"`
	PublishedAt sql.NullTime `json:"published_at"`
}

func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, upsertPost,
		arg.SourceID,
		arg.ExternalID,
		arg.RawText,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalID,
		&i.RawText,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.Status,
	)
	return i, err
}
