// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const claimScheduledPost = `-- name: ClaimScheduledPost :one
UPDATE posts SET status = 'sending'
WHERE id = ? AND status = 'scheduled'
RETURNING id, source_id, external_id, raw_text, published_at, fetched_at, status, retry_count
`

func (q *Queries) ClaimScheduledPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, claimScheduledPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalID,
		&i.RawText,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.Status,
		&i.RetryCount,
	)
	return i, err
}

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts WHERE status <> 'fetch_error'
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsBySource = `-- name: CountPostsBySource :one
SELECT COUNT(*) FROM posts WHERE source_id = ? AND status <> 'fetch_error'
`

func (q *Queries) CountPostsBySource(ctx context.Context, sourceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsBySource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPost = `-- name: GetPost :one
SELECT id, source_id, external_id, raw_text, published_at, fetched_at, status, retry_count FROM posts WHERE id = ?
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalID,
		&i.RawText,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.Status,
		&i.RetryCount,
	)
	return i, err
}

const getPostWithSource = `-- name: GetPostWithSource :one
SELECT p.id, p.source_id, p.external_id, p.raw_text, p.published_at, p.fetched_at, p.status, p.retry_count, s.channel_handle FROM posts p
JOIN sources s ON s.id = p.source_id
WHERE p.id = ?
`

type GetPostWithSourceRow struct {
	ID            int64        `json:"id"`
	SourceID      int64        `json:"source_id"`
	ExternalID    string       `json:"external_id"`
	RawText       string       `json:"raw_text"`
	PublishedAt   sql.NullTime `json:"published_at"`
	FetchedAt     time.Time    `json:"fetched_at"`
	Status        string       `json:"status"`
	RetryCount    int64        `json:"retry_count"`
	ChannelHandle string       `json:"channel_handle"`
}

func (q *Queries) GetPostWithSource(ctx context.Context, id int64) (GetPostWithSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getPostWithSource, id)
	var i GetPostWithSourceRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalID,
		&i.RawText,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.Status,
		&i.RetryCount,
		&i.ChannelHandle,
	)
	return i, err
}

const getRetrieablePosts = `-- name: GetRetrieablePosts :many
SELECT id, source_id, external_id, raw_text, published_at, fetched_at, status, retry_count FROM posts WHERE status = 'fetch_error' AND retry_count < ?
`

func (q *Queries) GetRetrieablePosts(ctx context.Context, retryCount int64) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getRetrieablePosts, retryCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ExternalID,
			&i.RawText,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.Status,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hidePost = `-- name: HidePost :exec
UPDATE posts SET status = 'skipped' WHERE id = ?
`

func (q *Queries) HidePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, hidePost, id)
	return err
}

const incrementRetryCount = `-- name: IncrementRetryCount :exec
UPDATE posts SET retry_count = retry_count + 1 WHERE id = ?
`

func (q *Queries) IncrementRetryCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementRetryCount, id)
	return err
}

const listPostsBySource = `-- name: ListPostsBySource :many
SELECT p.id, p.source_id, p.external_id, p.raw_text, p.published_at, p.fetched_at, p.status, p.retry_count, s.channel_handle FROM posts p
JOIN sources s ON s.id = p.source_id
WHERE p.source_id = ?
  AND p.status <> 'fetch_error'
ORDER BY p.published_at DESC
LIMIT ? OFFSET ?
`

type ListPostsBySourceParams struct {
	SourceID int64 `json:"source_id"`
	Limit    int64 `json:"limit"`
	Offset   int64 `json:"offset"`
}

type ListPostsBySourceRow struct {
	ID            int64        `json:"id"`
	SourceID      int64        `json:"source_id"`
	ExternalID    string       `json:"external_id"`
	RawText       string       `json:"raw_text"`
	PublishedAt   sql.NullTime `json:"published_at"`
	FetchedAt     time.Time    `json:"fetched_at"`
	Status        string       `json:"status"`
	RetryCount    int64        `json:"retry_count"`
	ChannelHandle string       `json:"channel_handle"`
}

func (q *Queries) ListPostsBySource(ctx context.Context, arg ListPostsBySourceParams) ([]ListPostsBySourceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsBySource, arg.SourceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsBySourceRow
	for rows.Next() {
		var i ListPostsBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ExternalID,
			&i.RawText,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.Status,
			&i.RetryCount,
			&i.ChannelHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsLatest = `-- name: ListPostsLatest :many
SELECT p.id, p.source_id, p.external_id, p.raw_text, p.published_at, p.fetched_at, p.status, p.retry_count, s.channel_handle FROM posts p
JOIN sources s ON s.id = p.source_id
WHERE p.status <> 'fetch_error'
ORDER BY p.published_at DESC
LIMIT ? OFFSET ?
`

type ListPostsLatestParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListPostsLatestRow struct {
	ID            int64        `json:"id"`
	SourceID      int64        `json:"source_id"`
	ExternalID    string       `json:"external_id"`
	RawText       string       `json:"raw_text"`
	PublishedAt   sql.NullTime `json:"published_at"`
	FetchedAt     time.Time    `json:"fetched_at"`
	Status        string       `json:"status"`
	RetryCount    int64        `json:"retry_count"`
	ChannelHandle string       `json:"channel_handle"`
}

func (q *Queries) ListPostsLatest(ctx context.Context, arg ListPostsLatestParams) ([]ListPostsLatestRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsLatest, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsLatestRow
	for rows.Next() {
		var i ListPostsLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ExternalID,
			&i.RawText,
			&i.PublishedAt,
			&i.FetchedAt,
			&i.Status,
			&i.RetryCount,
			&i.ChannelHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPostArchived = `-- name: MarkPostArchived :exec
UPDATE posts SET status = 'archived' WHERE id = ?
`

func (q *Queries) MarkPostArchived(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostArchived, id)
	return err
}

const markPostFailed = `-- name: MarkPostFailed :exec
UPDATE posts SET status = 'fetch_error' WHERE id = ?
`

func (q *Queries) MarkPostFailed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostFailed, id)
	return err
}

const markPostScheduled = `-- name: MarkPostScheduled :exec
UPDATE posts SET status = 'scheduled' WHERE id = ?
`

func (q *Queries) MarkPostScheduled(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostScheduled, id)
	return err
}

const markPostSending = `-- name: MarkPostSending :exec
UPDATE posts SET status = 'sending' WHERE id = ?
`

func (q *Queries) MarkPostSending(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostSending, id)
	return err
}

const markPostSent = `-- name: MarkPostSent :exec
UPDATE posts SET status = 'sent' WHERE id = ?
`

func (q *Queries) MarkPostSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostSent, id)
	return err
}

const unhidePost = `-- name: UnhidePost :exec
UPDATE posts SET status = 'new' WHERE id = ?
`

func (q *Queries) UnhidePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, unhidePost, id)
	return err
}

const upsertPost = `-- name: UpsertPost :one
INSERT INTO posts (source_id, external_id, raw_text, published_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(source_id, external_id) DO NOTHING
RETURNING id, source_id, external_id, raw_text, published_at, fetched_at, status, retry_count
`

type UpsertPostParams struct {
	SourceID    int64        `json:"source_id"`
	ExternalID  string       `json:"external_id"`
	RawText     string       `json:"raw_text"`
	PublishedAt sql.NullTime `json:"published_at"`
}

func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, upsertPost,
		arg.SourceID,
		arg.ExternalID,
		arg.RawText,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalID,
		&i.RawText,
		&i.PublishedAt,
		&i.FetchedAt,
		&i.Status,
		&i.RetryCount,
	)
	return i, err
}
