// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddAllowedUser(ctx context.Context, arg AddAllowedUserParams) error
	GetAllowedUser(ctx context.Context, userID int64) (GetAllowedUserRow, error)
	UpsertPost(ctx context.Context, arg UpsertPostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
