// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const claimDueSchedule = `-- name: ClaimDueSchedule :one
UPDATE schedule SET status = 'sending'
WHERE id = ? AND status = 'pending'
RETURNING id, draft_id, target_chat_id, scheduled_at, status, sent_at
`

func (q *Queries) ClaimDueSchedule(ctx context.Context, id int64) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, claimDueSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.TargetChatID,
		&i.ScheduledAt,
		&i.Status,
		&i.SentAt,
	)
	return i, err
}

const countScheduled = `-- name: CountScheduled :one
SELECT COUNT(*) FROM schedule
`

func (q *Queries) CountScheduled(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScheduled)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSchedule = `-- name: CreateSchedule :exec
INSERT INTO schedule (
  draft_id, target_chat_id, scheduled_at
) VALUES (
  ?, ?, ?
)
`

type CreateScheduleParams struct {
	DraftID      int64     `json:"draft_id"`
	TargetChatID int64     `json:"target_chat_id"`
	ScheduledAt  time.Time `json:"scheduled_at"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.ExecContext(ctx, createSchedule, arg.DraftID, arg.TargetChatID, arg.ScheduledAt)
	return err
}

const listDuePending = `-- name: ListDuePending :many
SELECT id, draft_id, target_chat_id, scheduled_at, status, sent_at FROM schedule WHERE scheduled_at <= ? ORDER BY scheduled_at DESC
`

func (q *Queries) ListDuePending(ctx context.Context, scheduledAt time.Time) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listDuePending, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.TargetChatID,
			&i.ScheduledAt,
			&i.Status,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledLatest = `-- name: ListScheduledLatest :many
SELECT s.id, s.draft_id, s.target_chat_id, s.scheduled_at, s.status, s.sent_at, d.final_text FROM schedule s
JOIN drafts d ON d.id = s.draft_id
ORDER BY s.scheduled_at DESC
LIMIT ? OFFSET ?
`

type ListScheduledLatestParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListScheduledLatestRow struct {
	ID           int64        `json:"id"`
	DraftID      int64        `json:"draft_id"`
	TargetChatID int64        `json:"target_chat_id"`
	ScheduledAt  time.Time    `json:"scheduled_at"`
	Status       string       `json:"status"`
	SentAt       sql.NullTime `json:"sent_at"`
	FinalText    string       `json:"final_text"`
}

func (q *Queries) ListScheduledLatest(ctx context.Context, arg ListScheduledLatestParams) ([]ListScheduledLatestRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledLatest, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledLatestRow
	for rows.Next() {
		var i ListScheduledLatestRow
		if err := rows.Scan(
			&i.ID,
			&i.DraftID,
			&i.TargetChatID,
			&i.ScheduledAt,
			&i.Status,
			&i.SentAt,
			&i.FinalText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduleSent = `-- name: MarkScheduleSent :exec
UPDATE schedule SET status = 'sent', sent_at = CURRENT_TIMESTAMP
WHERE id = ? AND status = 'sending'
`

func (q *Queries) MarkScheduleSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markScheduleSent, id)
	return err
}

const resetScheduleStatus = `-- name: ResetScheduleStatus :exec
UPDATE schedule SET status = 'pending' WHERE id = ?
`

func (q *Queries) ResetScheduleStatus(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetScheduleStatus, id)
	return err
}
