// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (channel_handle, active) VALUES (?, ?) RETURNING id, channel_handle, active
`

type CreateSourceParams struct {
	ChannelHandle string `json:"channel_handle"`
	Active        int64  `json:"active"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource, arg.ChannelHandle, arg.Active)
	var i Source
	err := row.Scan(&i.ID, &i.ChannelHandle, &i.Active)
	return i, err
}

const getActiveSources = `-- name: GetActiveSources :many
SELECT id, channel_handle, active FROM sources WHERE active = 1
`

func (q *Queries) GetActiveSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(&i.ID, &i.ChannelHandle, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
