// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const addAllowedUser = `-- name: AddAllowedUser :exec
INSERT INTO allowed_users (user_id, username) VALUES (?, ?)
ON CONFLICT(user_id) DO NOTHING
`

type AddAllowedUserParams struct {
	UserID   int64          `json:"user_id"`
	Username sql.NullString `json:"username"`
}

func (q *Queries) AddAllowedUser(ctx context.Context, arg AddAllowedUserParams) error {
	_, err := q.db.ExecContext(ctx, addAllowedUser, arg.UserID, arg.Username)
	return err
}

const getAllowedUser = `-- name: GetAllowedUser :one
SELECT user_id, username, lang FROM allowed_users WHERE user_id = ?
`

type GetAllowedUserRow struct {
	UserID   int64          `json:"user_id"`
	Username sql.NullString `json:"username"`
	Lang     string         `json:"lang"`
}

func (q *Queries) GetAllowedUser(ctx context.Context, userID int64) (GetAllowedUserRow, error) {
	row := q.db.QueryRowContext(ctx, getAllowedUser, userID)
	var i GetAllowedUserRow
	err := row.Scan(&i.UserID, &i.Username, &i.Lang)
	return i, err
}
