// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const addAllowedUser = `-- name: AddAllowedUser :exec
INSERT INTO allowed_users (user_id, username) VALUES (?, ?)
ON CONFLICT(user_id) DO NOTHING
`

type AddAllowedUserParams struct {
	UserID   int64          `json:"user_id"`
	Username sql.NullString `json:"username"`
}

func (q *Queries) AddAllowedUser(ctx context.Context, arg AddAllowedUserParams) error {
	_, err := q.db.ExecContext(ctx, addAllowedUser, arg.UserID, arg.Username)
	return err
}

const isAllowedUser = `-- name: IsAllowedUser :one
SELECT EXISTS(SELECT 1 FROM allowed_users WHERE user_id = ?) AS allowed
`

func (q *Queries) IsAllowedUser(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAllowedUser, userID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}
